apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.smsforwarder.smslistener'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()

android {
  namespace "com.smsforwarder.smslistener"
  compileSdkVersion 35

  defaultConfig {
    minSdkVersion 30
    targetSdkVersion 35
  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }

  kotlinOptions {
    jvmTarget = "17"
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"
}
